[package]
name = "rivulet"
version = "0.1.0"
publish = false
authors = ["Machine Phase Systems <hello@machinephase.systems>"]
license = "MPL-2.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
