name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Check syntax
      run: cargo check

    - name: Run tests
      run: cargo test --workspace --all-features

    - name: Run linter
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Check documentation
      run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps
