name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-build-

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy, llvm-tools-preview

    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov

    - name: Check syntax
      run: cargo check

    - name: Run tests
      run: cargo test --workspace --all-features

    - name: Run linter
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Check documentation
      run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --no-deps

    - name: Check code coverage
      run: cargo llvm-cov --workspace --all-features --fail-uncovered-lines 0 --fail-uncovered-regions 0 --fail-uncovered-functions 0 --show-missing-lines

  book:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v2
      with:
        mdbook-version: 'latest'

    - name: Build mdBook
      run: |
        cd book
        mdbook build

    - name: Test mdBook
      run: |
        cd book
        mdbook test
